<!DOCTYPE html>
<html lang="en"><head>
<script src="linear_regression_files/libs/clipboard/clipboard.min.js"></script>
<script src="linear_regression_files/libs/quarto-html/tabby.min.js"></script>
<script src="linear_regression_files/libs/quarto-html/popper.min.js"></script>
<script src="linear_regression_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="linear_regression_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="linear_regression_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="linear_regression_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <title>Linear Regression</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="linear_regression_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="linear_regression_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="linear_regression_files/libs/revealjs/dist/theme/quarto-5de8172cf71ca609c2e175cde40b2aa9.css">
  <link href="linear_regression_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="linear_regression_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="linear_regression_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="linear_regression_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-position="50% 75%" data-background-size="12%" class="quarto-title-block center">
  <h1 class="title">Linear Regression</h1>
  <p class="subtitle">ISI-BUDS 2026</p>

<div class="quarto-title-authors">
</div>

</section>
<section id="overview" class="slide level2">
<h2>Overview</h2>
<ul>
<li class="fragment">Simple linear regression models with one binary explanatory variable</li>
<li class="fragment">Statistical inference using linear regression models</li>
<li class="fragment">Simple linear regression models with one numerical explanatory variable</li>
<li class="fragment">Model assessment and diagnostics</li>
<li class="fragment">Multiple linear regression models</li>
</ul>
</section>
<section id="introduction" class="slide level2">
<h2>Introduction</h2>
<ul>
<li class="fragment"><p>We discuss <strong>linear regression models</strong> for either testing a hypothesis regarding the relationship between one or more <strong>explanatory variables</strong> and a response variable, or <strong>estimating</strong> (predicting) unknown values of the response variable using one or more <strong>predictors</strong>.</p></li>
<li class="fragment"><p>We use <span class="math inline">\(X\)</span> to denote explanatory variables and <span class="math inline">\(Y\)</span> to denote response variables.</p></li>
<li class="fragment"><p>We start by focusing on problems where the explanatory variable is binary.</p></li>
<li class="fragment"><p>We then continue our discussion for situations where the explanatory variable is numerical.</p></li>
</ul>
</section>
<section>
<section id="single-binary-explanatory-variable" class="title-slide slide level1 center">
<h1><strong>Single Binary Explanatory Variable</strong></h1>

</section>
<section id="blood-pressure-and-salt-consumption" class="slide level2">
<h2>Blood Pressure and Salt Consumption</h2>
<ul>
<li class="fragment"><p>Suppose that we want to investigate the relationship between sodium chloride (salt) consumption (low vs.&nbsp;high consumption) and blood pressure among elderly people (e.g., above 65 years old).</p></li>
<li class="fragment"><p>We have a data set that contains the blood pressure of 25 elderly people with either a low or high sodium chloride diet.</p></li>
<li class="fragment"><p>The data set is called <strong>salt</strong> and contains the following variables:</p>
<ul>
<li class="fragment"><strong>bp</strong>: blood pressure (in mmHg)</li>
<li class="fragment"><strong>salt_level</strong>: sodium chloride diet (low vs.&nbsp;high)</li>
</ul></li>
</ul>
</section>
<section id="blood-pressure-and-salt-consumption-1" class="slide level2">
<h2>Blood Pressure and Salt Consumption</h2>

<img data-src="linear_regression_files/figure-revealjs/unnamed-chunk-2-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="blood-pressure-and-salt-consumption-2" class="slide level2">
<h2>Blood Pressure and Salt Consumption</h2>

<img data-src="linear_regression_files/figure-revealjs/unnamed-chunk-3-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="mean-trend" class="slide level2">
<h2>Mean Trend</h2>

<img data-src="linear_regression_files/figure-revealjs/unnamed-chunk-4-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="regression-line" class="slide level2">
<h2>Regression Line</h2>
<ul>
<li class="fragment"><p>Using the <strong>intercept</strong> <span class="math inline">\(a\)</span> and <strong>slope</strong> <span class="math inline">\(b\)</span>, we can write the equation for the straight line that connects the estimates of the response variable for different values of <span class="math inline">\(X\)</span> as follows: <span class="math display">\[{\hat{y}}  =  a + b x.\]</span></p></li>
<li class="fragment"><p>The above equation specifies a straight line called the <strong>regression line</strong>.</p></li>
<li class="fragment"><p>The regression line captures the linear relationship between the response variable (here, blood pressure) and the explanatory variable (here, low vs.&nbsp;high sodium chloride diet).</p></li>
</ul>
</section>
<section id="regression-line-1" class="slide level2">
<h2>Regression Line</h2>
<ul>
<li class="fragment"><p>For this example, <span class="math display">\[\begin{equation*}
\hat{y}  =  133.17 + 6.25 x.
\end{equation*}\]</span></p></li>
<li class="fragment"><p>We <em>expect</em> that on average the blood pressure increases by 6.25 units for <em>one unit increase</em> in <span class="math inline">\(X\)</span>.</p></li>
<li class="fragment"><p>In this case, one unit increase in <span class="math inline">\(X\)</span> from 0 to 1 means moving from low to high sodium chloride diet group.</p></li>
</ul>
</section>
<section id="estimation-and-prediction" class="slide level2">
<h2>Estimation and Prediction</h2>
<ul>
<li class="fragment"><p>For an individual with <span class="math inline">\(x=0\)</span> (i.e., low sodium chloride diet), the estimate (expected value) of blood pressure according to the above regression line is <span class="math display">\[\begin{eqnarray*}
\hat{y} &amp; = &amp; a + b \times 0 = a \\
&amp; = &amp; \hat{y}_{x=0},
\end{eqnarray*}\]</span> which is the sample mean for the first group.</p></li>
<li class="fragment"><p>For an individual with <span class="math inline">\(x=1\)</span> (i.e., high sodium chloride diet), the estimate according to the above regression line is <span class="math display">\[\begin{eqnarray*}
\hat{y} &amp; = &amp; a + b \times 1 = a+b \\
&amp; = &amp; \hat{y}_{x=1}.
\end{eqnarray*}\]</span></p></li>
</ul>
</section>
<section id="residual" class="slide level2">
<h2>Residual</h2>
<ul>
<li class="fragment"><p>We refer to the difference between the observed and estimated values of the response variable as the <strong>residual</strong>.</p></li>
<li class="fragment"><p>For individual <span class="math inline">\(i\)</span>, we denote the residual <span class="math inline">\(e_{i}\)</span> and calculate it as follows: <span class="math display">\[\begin{equation*}
  e_{i}  =  y_{i} - \hat{y}_{i}.
\end{equation*}\]</span></p></li>
<li class="fragment"><p>For instance, if someone belongs to the first group, her estimated blood pressure is <span class="math inline">\(\hat{y}_{i} = a =133.17\)</span>.</p></li>
<li class="fragment"><p>Now if the observed value of her blood pressure is <span class="math inline">\(y_{i} =
135.08\)</span>, then the residual is <span class="math display">\[\begin{equation*}
  e_{i}  = 135.08 - 133.17 = 1.91.
\end{equation*}\]</span></p></li>
</ul>
</section>
<section id="residual-sum-of-squares-rss" class="slide level2">
<h2>Residual Sum of Squares (RSS)</h2>
<ul>
<li class="fragment"><p>As a measure of discrepancy between the observed values and those estimated by the line, we calculate the <strong>Residual Sum of Squares</strong> (RSS): <span class="math display">\[\begin{equation*}
\mathit{RSS} =  \sum_{i}^{n} e_{i}^{2}.
\label{RSS}
\end{equation*}\]</span></p></li>
<li class="fragment"><p>Among all possible straight lines we could have drawn, the linear regression line provides the smallest value of RSS.</p></li>
<li class="fragment"><p>Therefore, the above approach for finding the regression line is called the <strong>least-squares</strong> method, and the resulting line is called the <strong>least-squares</strong> regression line.</p></li>
</ul>
</section></section>
<section>
<section id="inference" class="title-slide slide level1 center">
<h1><strong>Inference</strong></h1>

</section>
<section id="statistical-inference-using-simple-linear-regression-models" class="slide level2">
<h2>Statistical Inference Using Simple Linear Regression Models</h2>
<ul>
<li class="fragment"><p>We discussed fitting a regression line to observed data with one numerical response variable and one binary explanatory variable.</p></li>
<li class="fragment"><p>As usual, we would like to extend our findings to the entire population, i.e., <strong>perform statistical inference</strong>.</p></li>
<li class="fragment"><p>More specifically, we want to <strong>predict</strong> the unknown value of the response variable in the population, <strong>estimate</strong> regression parameters, and <strong>test hypotheses</strong> regarding the relationship between the response and explanatory variables.</p></li>
</ul>
</section>
<section id="statistical-inference-using-simple-linear-regression-models-1" class="slide level2">
<h2>Statistical Inference Using Simple Linear Regression Models</h2>
<ul>
<li class="fragment"><p>We start by extending our regression model to the whole population.</p></li>
<li class="fragment"><p>Recall that <span class="math display">\[\begin{eqnarray*}
e_{i}  &amp; = &amp; y_{i} - \hat{y}_{i}\\
\hat{y}_{i} &amp; = &amp; a + b x_{i}
\end{eqnarray*}\]</span></p></li>
</ul>
</section>
<section id="statistical-inference-using-simple-linear-regression-models-2" class="slide level2">
<h2>Statistical Inference Using Simple Linear Regression Models</h2>
<ul>
<li class="fragment"><p>Based on this line, we can write the value of the response variable for individual <span class="math inline">\(i\)</span> in terms of the above regression line and the residual: <span class="math display">\[\begin{equation*}
y_{i} = a + b x_{i} + e_{i}.
\end{equation*}\]</span></p></li>
<li class="fragment"><p>For the whole population we write the model as follows: <span class="math display">\[\begin{equation*}
Y = \alpha + \beta X + \epsilon
\end{equation*}\]</span></p></li>
</ul>
</section>
<section id="simple-linear-regression-models" class="slide level2">
<h2>Simple Linear Regression Models</h2>
<ul>
<li class="fragment"><p>We refer to the above equation as the <strong>linear regression model</strong>.</p></li>
<li class="fragment"><p>More specifically, we call it the <strong>simple linear regression model</strong> since there is only one explanatory variable.</p></li>
<li class="fragment"><p>We refer to <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> as the <strong>regression parameters</strong>. More specifically, <span class="math inline">\(\beta\)</span> is called the <strong>regression coefficient</strong> for the explanatory variable.</p></li>
<li class="fragment"><p><span class="math inline">\(\epsilon\)</span> is called the <strong>error term</strong>, representing the difference between the estimated (based on the regression line for the entire population) and the actual values of <span class="math inline">\(Y\)</span> in the population.</p></li>
</ul>
</section>
<section id="estimating-regression-parameters" class="slide level2">
<h2>Estimating Regression Parameters</h2>
<ul>
<li class="fragment"><p>The slope <span class="math inline">\(a\)</span> and the intercept <span class="math inline">\(b\)</span> provide <strong>point estimates</strong> for regression parameters <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span>.</p></li>
<li class="fragment"><p>Point estimates, however, do not reflect the extent of our uncertainty. Therefore, we find <strong>interval estimates</strong> based on confidence intervals.</p></li>
<li class="fragment"><p>Confidence intervals: <span class="math display">\[\begin{equation*}
[b - t_{\mathrm{crit}} \times \mathit{SE}_{b}, b + t_{\mathrm{crit}} \times \mathit{SE}_{b}].
\end{equation*}\]</span></p></li>
<li class="fragment"><p>For simple linear regression models, the standard error <span class="math inline">\(\mathit{SE}_{b}\)</span> is <span class="math display">\[\begin{equation*}
\mathit{SE}_{b}  =
  \frac{\sqrt{\mathit{RSS}/(n-2)}}{\sqrt{\sum_{i} (x_{i} - \bar{x})^2}}
\end{equation*}\]</span></p></li>
</ul>
</section>
<section id="fitting-a-linear-regression-model-in-r" class="slide level2">
<h2>Fitting a Linear Regression Model in R</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(bp <span class="sc">~</span> salt_level, <span class="at">data =</span> salt)</span>
<span id="cb1-2"><a href=""></a><span class="fu">summary</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bp ~ salt_level, data = salt)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.2990 -3.5627  0.6873  3.2110  5.5910 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     133.173      1.007 132.222  &lt; 2e-16 ***
salt_levelhigh    6.256      1.593   3.929 0.000672 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.901 on 23 degrees of freedom
Multiple R-squared:  0.4016,    Adjusted R-squared:  0.3756 
F-statistic: 15.43 on 1 and 23 DF,  p-value: 0.0006716</code></pre>
</div>
</div>
</section>
<section id="fitting-a-linear-regression-model-in-r-1" class="slide level2">
<h2>Fitting a Linear Regression Model in R</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a><span class="fu">confint</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    2.5 %     97.5 %
(Intercept)    131.089133 135.256200
salt_levelhigh   2.961978   9.550689</code></pre>
</div>
</div>
</section>
<section id="hypothesis-testing-with-simple-linear-regression-models" class="slide level2">
<h2>Hypothesis Testing with Simple Linear Regression Models</h2>
<ul>
<li class="fragment"><p>Linear regression models can be used for testing hypotheses regarding possible linear relationship between the response variable and the explanatory variable.</p></li>
<li class="fragment"><p>The null hypothesis stating no <em>linear</em> relationship between the two variable can be written as <span class="math inline">\(H_{0}: \beta=0\)</span>.</p></li>
<li class="fragment"><p>Similar to the two sample t-test, we first find the <span class="math inline">\(t\)</span>-score.</p></li>
<li class="fragment"><p>Then, we find the <span class="math inline">\(p\)</span>-value (i.e., the observed significance level) by calculating the probability of as or more extreme values than <span class="math inline">\(t\)</span>-score under the null hypothesis.</p></li>
</ul>
</section>
<section id="hypothesis-testing-with-simple-linear-regression-models-1" class="slide level2">
<h2>Hypothesis Testing with Simple Linear Regression Models</h2>
<ul>
<li class="fragment"><p>For linear regression models, the <span class="math inline">\(t\)</span>-score is <span class="math display">\[\begin{equation*}
t  =  \frac{b}{\mathit{SE}_{b}}.
\end{equation*}\]</span></p></li>
<li class="fragment"><p>We find the corresponding <span class="math inline">\(p\)</span>-value as follows:</p>
<span class="math display">\[\begin{array}{l@{\quad}l}
    \mbox{if}\ H_{A}: \beta &lt; 0, &amp; p_{\mathrm{obs}} = P(T \leq t), \\
    \mbox{if}\ H_{A}: \beta &gt; 0, &amp; p_{\mathrm{obs}} = P(T \geq t ), \\
    \mbox{if}\ H_{A}: \beta \ne 0, &amp; p_{\mathrm{obs}} = 2 \times P\bigl(T \geq | t | \bigr),
\end{array}\]</span></li>
<li class="fragment"><p><span class="math inline">\(T\)</span> has a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom.</p></li>
</ul>
</section></section>
<section>
<section id="numerical-explanatory-variable" class="title-slide slide level1 center">
<h1><strong>Numerical Explanatory Variable</strong></h1>

</section>
<section id="one-numerical-explanatory-variable" class="slide level2">
<h2>One Numerical Explanatory Variable</h2>
<ul>
<li class="fragment">We now discuss simple linear regression models (i.e., linear regression with only one explanatory variable), where the explanatory variable is numerical.</li>
</ul>
</section>
<section id="blood-pressure-and-salt-consumption-3" class="slide level2">
<h2>Blood pressure and salt consumption</h2>

<img data-src="linear_regression_files/figure-revealjs/unnamed-chunk-7-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="blood-pressure-and-salt-consumption-4" class="slide level2">
<h2>Blood pressure and salt consumption</h2>
<ul>
<li class="fragment"><p>As before, we want to find a straight line that captures the relationship between the two variables.</p></li>
<li class="fragment"><p>Similar to what we discussed before, among all possible lines we can pass through the data, we choose the <em>least-squares regression line</em>, which is the one with the <em>smallest sum of squared residuals</em>.</p></li>
</ul>
</section>
<section id="blood-pressure-and-salt-consumption-5" class="slide level2">
<h2>Blood pressure and salt consumption</h2>

<img data-src="linear_regression_files/figure-revealjs/unnamed-chunk-8-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="one-numerical-explanatory-variable-1" class="slide level2">
<h2>One Numerical Explanatory Variable</h2>
<ul>
<li class="fragment"><p>First, we find the slope of regression line using the sample correlation coefficient, <span class="math inline">\(r\)</span>, and the sample standard deviation of <span class="math inline">\(Y\)</span> of <span class="math inline">\(X\)</span>, denoted as <span class="math inline">\(s_{y}\)</span> and <span class="math inline">\(s_x\)</span> respectively, <span class="math display">\[\begin{equation*}
b  =  r \frac{s_{y}}{s_{x}}.
\end{equation*}\]</span></p></li>
<li class="fragment"><p>After finding the slope, we find the intercept as follows: <span class="math display">\[\begin{equation*}
a  =  \bar{y} - b \bar{x},
\end{equation*}\]</span> where <span class="math inline">\(\bar{y}\)</span> and <span class="math inline">\(\bar{x}\)</span> are the sample means</p></li>
<li class="fragment"><p>For our example, <span class="math inline">\(a=128.6\)</span> and <span class="math inline">\(b = 1.2\)</span>.</p></li>
</ul>
</section>
<section id="residual-1" class="slide level2">
<h2>Residual</h2>
<ul>
<li class="fragment"><p>Given <span class="math inline">\(x\)</span>, we can find the expected value of <span class="math inline">\(y\)</span> for each subject.</p></li>
<li class="fragment"><p>For one individual in our sample, the amount of daily sodium chloride intake is <span class="math inline">\(x_{i} = 3.68\)</span>.</p></li>
<li class="fragment"><p>The estimated value of the blood pressure for this person is <span class="math display">\[\begin{equation*}
\hat{y}_{i}  =  128.60 + 1.20 \times 3.68 = 133.02.
\end{equation*}\]</span></p></li>
<li class="fragment"><p>The actual blood pressure for this individual is <span class="math inline">\(y_{i} = 128.3\)</span>. The residual therefore is <span class="math display">\[\begin{equation*}
e_{i} = y_{i} - \hat{y}_{i} = 128.3 - 133.02 = - 4.72.
\end{equation*}\]</span></p></li>
</ul>
</section>
<section id="prediction" class="slide level2">
<h2>Prediction</h2>
<ul>
<li class="fragment"><p>We can also use our model for <strong>predicting</strong> the unknown values of the response variable (i.e., blood pressure) for all individuals in the target population.</p></li>
<li class="fragment"><p>For example, if we know the amount of daily sodium chloride intake is <span class="math inline">\(x=7.81\)</span> for an individual, we can predict her blood pressure as follows: <span class="math display">\[\begin{equation*}
\hat{y}  =  128.60 + 1.20 \times 7.81 = 137.97.
\end{equation*}\]</span></p></li>
</ul>
</section>
<section id="interpretation" class="slide level2">
<h2>Interpretation</h2>
<ul>
<li class="fragment"><p>The interpretation of the intercept <span class="math inline">\(a\)</span> and the slope <span class="math inline">\(b\)</span> is similar to what we had before.</p></li>
<li class="fragment"><p><span class="math inline">\(a=128.6\)</span>: the <em>expected</em> value of blood pressure is 128.6 for subjects with zero sodium chloride diet.</p></li>
<li class="fragment"><p><span class="math inline">\(b=1.2\)</span>: the <em>expected</em> value of blood pressure increases by 1.2 points corresponding to one unit increase in the daily amount of sodium chloride intake.</p></li>
</ul>
</section>
<section id="confidence-interval" class="slide level2">
<h2>Confidence Interval</h2>
<ul>
<li class="fragment"><p>As mentioned above, <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> are the point estimates for the regression parameters <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span>, <span class="math display">\[\begin{equation*}
Y = \alpha + \beta X + \epsilon
\end{equation*}\]</span></p></li>
<li class="fragment"><p>Finding confidence intervals for regression parameters <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> also remains as before.</p></li>
<li class="fragment"><p>More specifically, the confidence interval for regression coefficient is obtained as follows: <span class="math display">\[\begin{eqnarray*}
[b - t_{\mathrm{crit}} \times \mathit{SE}_{b}, b + t_{\mathrm{crit}} \times \mathit{SE}_{b}].
\end{eqnarray*}\]</span></p></li>
</ul>
</section>
<section id="hypothesis-testing" class="slide level2">
<h2>Hypothesis Testing</h2>
<ul>
<li class="fragment"><p>The steps for performing hypothesis testing regarding the linear relationship between the response and explanatory variables also remain the same.</p></li>
<li class="fragment"><p>The null hypothesis is <span class="math inline">\(H_{0}: \beta = 0\)</span>, which indicates that the two variables are not linearly related.</p></li>
<li class="fragment"><p>To evaluate this hypothesis, we need to find the <span class="math inline">\(t\)</span>-score first, <span class="math display">\[\begin{equation*}
t  =  \frac{b}{\mathit{SE}_{b}}.
\end{equation*}\]</span></p></li>
</ul>
</section>
<section id="statistical-inference-using-regression-models" class="slide level2">
<h2>Statistical inference using regression models</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(bp <span class="sc">~</span> salt, <span class="at">data =</span> salt)</span>
<span id="cb5-2"><a href=""></a><span class="fu">summary</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bp ~ salt, data = salt)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.0388 -1.6755  0.3662  1.8824  5.3443 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  128.616      1.102 116.723  &lt; 2e-16 ***
salt           1.197      0.162   7.389 1.63e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.745 on 23 degrees of freedom
Multiple R-squared:  0.7036,    Adjusted R-squared:  0.6907 
F-statistic: 54.59 on 1 and 23 DF,  p-value: 1.631e-07</code></pre>
</div>
</div>
</section>
<section id="statistical-inference-using-regression-models-1" class="slide level2">
<h2>Statistical inference using regression models</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href=""></a><span class="fu">confint</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %     97.5 %
(Intercept) 126.3369606 130.895834
salt          0.8617951   1.531993</code></pre>
</div>
</div>
</section>
<section id="goodness-of-fit" class="slide level2">
<h2>Goodness of Fit</h2>
<ul>
<li class="fragment"><p>We now want to examine how well the regression line represents the observed data; in other words, how well the regression model <strong>fits</strong> the data.</p></li>
<li class="fragment"><p>In statistics, we use <strong>goodness-of-fit</strong> measures for this purpose.</p></li>
<li class="fragment"><p>The residual sums of squares (RSS) can be interpreted as the <strong>unexplained variation</strong> or <strong>lack of fit</strong>.</p></li>
<li class="fragment"><p>The <strong>total variation</strong> in the response variable is measured by the <strong>Total Sum of Squares</strong> (TSS), <span class="math display">\[\begin{eqnarray*}
\mathit{TSS} &amp; = &amp; \sum_{i}^{n}(y_{i} - \bar{y})^{2}.
\end{eqnarray*}\]</span></p></li>
</ul>
</section>
<section id="goodness-of-fit-1" class="slide level2">
<h2>Goodness of Fit</h2>
<ul>
<li class="fragment"><p>The fraction <span class="math inline">\(\mathit{RSS}/\mathit{TSS}\)</span> can be interpreted as the percent of total variation that was not explained by the regression model.</p></li>
<li class="fragment"><p>In contrast, <span class="math inline">\(1 - \mathit{RSS}/\mathit{TSS}\)</span> is fraction of total variation explained by the model.</p></li>
<li class="fragment"><p>This fraction is <span class="math inline">\(R^{2}\)</span>, which measures the goodness of fit for the regression model, <span class="math display">\[\begin{eqnarray*}
R^{2} &amp; = &amp; 1 - \frac{\mathit{RSS}}{\mathit{TSS}}.
\end{eqnarray*}\]</span></p></li>
<li class="fragment"><p>For models with one numerical explanatory variable, <span class="math inline">\(R^{2}\)</span> is equal to the square of Pearson’s correlation coefficient <span class="math inline">\(r\)</span>.</p></li>
</ul>
</section>
<section id="model-assumptions-and-diagnostics" class="slide level2">
<h2>Model Assumptions and Diagnostics</h2>
<ul>
<li class="fragment"><p>The typical assumptions of linear regression models are</p>
<ul>
<li class="fragment"><p>Linearity</p></li>
<li class="fragment"><p>Independent observations</p></li>
<li class="fragment"><p>Constant variance and normality of the error term <span class="math display">\[\begin{eqnarray*}
\epsilon &amp; \sim &amp; N\bigl(0, \sigma^{2}\bigr).
\end{eqnarray*}\]</span></p></li>
</ul></li>
</ul>
</section>
<section id="model-assumptions-and-diagnostics-1" class="slide level2">
<h2>Model Assumptions and Diagnostics</h2>
<ul>
<li class="fragment"><p>We can use the <strong>residual plot</strong> to check the assumptions of linearity and constant variance.</p></li>
<li class="fragment"><p>The residual plot is a scatter plot of the residuals <span class="math inline">\(e_{i}\)</span> against the fitted values <span class="math inline">\(\hat{y}_{i}\)</span>.</p></li>
<li class="fragment"><p>If the assumptions of linearity and constant variance are satisfied, we expect the residuals to be randomly scattered around zero, with no discernible pattern.</p></li>
</ul>
</section>
<section id="model-assumptions-and-diagnostics-2" class="slide level2">
<h2>Model Assumptions and Diagnostics</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href=""></a><span class="fu">ggplot</span>(salt, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fitted</span>(model), <span class="at">y =</span> <span class="fu">resid</span>(model))) <span class="sc">+</span></span>
<span id="cb9-2"><a href=""></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb9-3"><a href=""></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb9-4"><a href=""></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Fitted Values"</span>, <span class="at">y =</span> <span class="st">"Residuals"</span>) <span class="sc">+</span></span>
<span id="cb9-5"><a href=""></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="linear_regression_files/figure-revealjs/unnamed-chunk-11-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="multiple-linear-regression" class="slide level2">
<h2>Multiple Linear Regression</h2>
<ul>
<li class="fragment"><p>So far, we have focused on linear regression models with only one explanatory variable.</p></li>
<li class="fragment"><p>In most cases, however, we are interested in the relationship between the response variable and multiple explanatory variables.</p></li>
<li class="fragment"><p>Such models with multiple explanatory variables or predictors are called <strong>multiple linear regression</strong> models.</p></li>
<li class="fragment"><p>For example, we might want to examine the relationship between babies’ birthweight and their mothers’ age and smoking status during pregnancy.</p></li>
</ul>
</section>
<section id="multiple-linear-regression-1" class="slide level2">
<h2>Multiple Linear Regression</h2>
<ul>
<li class="fragment"><p>A multiple linear regression model with <span class="math inline">\(p\)</span> explanatory variables can be presented as follows: <span class="math display">\[\begin{equation*}
Y  =  \alpha + \beta_{1} X_{1} + \beta_{2} X_{2} + \cdots + \beta_{p} X_{p} + \epsilon.
\end{equation*}\]</span></p></li>
<li class="fragment"><p>We use the least-squares method as before to estimate the model parameters, <span class="math display">\[\begin{equation*}
\hat{y}  =  a + b_{1}x_{1} + b_{2}x_{2} + \cdots + b_{p}x_{p}.
\end{equation*}\]</span></p></li>
</ul>
</section>
<section id="birthweight-and-smoking" class="slide level2">
<h2>Birthweight and Smoking</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href=""></a><span class="fu">library</span>(MASS)</span>
<span id="cb10-2"><a href=""></a><span class="fu">data</span>(<span class="st">"birthwt"</span>)</span>
<span id="cb10-3"><a href=""></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(bwt <span class="sc">~</span> age <span class="sc">+</span> <span class="fu">factor</span>(smoke), <span class="at">data=</span>birthwt)</span>
<span id="cb10-4"><a href=""></a><span class="fu">summary</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bwt ~ age + factor(smoke), data = birthwt)

Residuals:
     Min       1Q   Median       3Q      Max 
-2119.98  -442.66    52.92   532.38  1690.74 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    2791.224    240.950  11.584   &lt;2e-16 ***
age              11.290      9.881   1.143    0.255    
factor(smoke)1 -278.356    106.987  -2.602    0.010 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 717.2 on 186 degrees of freedom
Multiple R-squared:  0.04299,   Adjusted R-squared:  0.0327 
F-statistic: 4.177 on 2 and 186 DF,  p-value: 0.0168</code></pre>
</div>
</div>
</section>
<section id="interpretation-1" class="slide level2">
<h2>Interpretation</h2>
<ul>
<li class="fragment"><p>The intercept in multiple linear regression model is the expected (average) value of the response variable when all the explanatory variables in the model are set to zero simultaneously.</p></li>
<li class="fragment"><p>In the above example, the intercept is <span class="math inline">\(a=2791\)</span>, which is obtained by setting age and smoking to zero.</p></li>
<li class="fragment"><p>In this case, this is not a reasonable interpretation since mother’s age cannot be zero.</p></li>
</ul>
</section>
<section id="interpretation-2" class="slide level2">
<h2>Interpretation</h2>
<ul>
<li class="fragment"><p>We interpret <span class="math inline">\(b_{j}\)</span> as our estimate of the expected (average) change in the response variable associated with a unit increase in the corresponding explanatory variable <span class="math inline">\(x_{j}\)</span> <strong>while all other explanatory variables in the model remain fixed</strong>.</p></li>
<li class="fragment"><p>For the above example, the point estimate of the regression coefficient for <em>age</em> is <span class="math inline">\(b_{1}=11\)</span>, and the estimate of the regression coefficient for <em>smoke</em> is <span class="math inline">\(b_{2} = -278\)</span>.</p></li>
</ul>
</section>
<section id="interpretation-3" class="slide level2">
<h2>Interpretation</h2>
<ul>
<li class="fragment"><p>We expect that the birthweight of babies increase by 11 grams as the mother’s age increases by one year among mothers with the same smoking status.</p></li>
<li class="fragment"><p>The expected birthweight changes by <span class="math inline">\(-278\)</span> (decreases by <span class="math inline">\(278\)</span>) grams associated with one unit increase in the value of the variable <em>smoke</em> (i.e., going from non-smoking to smoking) among mothers with the same age.</p></li>
</ul>
</section>
<section id="additivity" class="slide level2">
<h2>Additivity</h2>
<ul>
<li class="fragment"><p>In multiple linear regression models, we usually assume that the effects of explanatory variables on the response variable are <strong>additive</strong>.</p></li>
<li class="fragment"><p>This means that the expected change in the response variable corresponding to one unit increase in one of the explanatory variables remains the same regardless of the values of other explanatory variables in the model.</p></li>
<li class="fragment"><p>In the next plot, nonsmoking mothers are shown as <em>circles</em>, while smoking mothers are shown as <em>squares</em>. The <em>dashed line</em> shows the regression line among nonsmoking mothers, and the <em>solid line</em> shows the regression line among the smoking mothers</p></li>
</ul>
</section>
<section id="additivity-1" class="slide level2">
<h2>Additivity</h2>
<p><em>circles</em>: nonsmoking mothers, <em>squares</em>: smoking mothers. <em>dashed line</em>: regression line among nonsmoking mothers, <em>solid line</em>: regression line among the smoking mothers</p>
<div class="v-center">
<p><img data-src="bwtByAgeSmokeLinReg.png" style="width:60.0%"></p>
</div>
</section>
<section id="interaction" class="slide level2">
<h2>Interaction</h2>
<ul>
<li class="fragment"><p>We might believe that the effects are not additive.</p></li>
<li class="fragment"><p>That is, the effect of one explanatory variable <span class="math inline">\(x_{1}\)</span> on the response variable depends on the value of another explanatory variable <span class="math inline">\(x_{2}\)</span> in the model.</p></li>
<li class="fragment"><p>We can still use linear regression models by including a new variable <span class="math inline">\(x_{3} = x_{1}x_{2}\)</span>, <span class="math display">\[\begin{eqnarray*}
\hat{y} = a + b_{1}x_{1} + b_{2}x_{2} + b_{12}x_{1}x_{2}
\end{eqnarray*}\]</span></p></li>
</ul>
</section>
<section id="interaction-1" class="slide level2">
<h2>Interaction</h2>
<ul>
<li class="fragment"><p>The term <span class="math inline">\(x_{1}x_{2}\)</span> is called the <strong>interaction term</strong>.</p></li>
<li class="fragment"><p>We refer to <span class="math inline">\(b_{1}\)</span> and <span class="math inline">\(b_{2}\)</span> as the <strong>main effects</strong>, and refer to <span class="math inline">\(b_{12}\)</span> as the <strong>interaction effect</strong>.</p></li>
<li class="fragment"><p>Note that when we include an interaction term in our model, we should be cautious about how we interpret model parameters.</p></li>
<li class="fragment"><p>In R, to fit models with interaction terms, we use “*” instead of “+” to separate variables.</p></li>
</ul>
</section>
<section id="interaction-2" class="slide level2">
<h2>Interaction</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href=""></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(bwt <span class="sc">~</span> <span class="fu">factor</span>(smoke) <span class="sc">*</span> age, <span class="at">data=</span>birthwt)</span>
<span id="cb12-2"><a href=""></a><span class="fu">summary</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bwt ~ factor(smoke) * age, data = birthwt)

Residuals:
     Min       1Q   Median       3Q      Max 
-2189.27  -458.46    51.46   527.26  1521.39 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         2406.06     292.19   8.235 3.18e-14 ***
factor(smoke)1       798.17     484.34   1.648   0.1011    
age                   27.73      12.15   2.283   0.0236 *  
factor(smoke)1:age   -46.57      20.45  -2.278   0.0239 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 709.3 on 185 degrees of freedom
Multiple R-squared:  0.06909,   Adjusted R-squared:  0.054 
F-statistic: 4.577 on 3 and 185 DF,  p-value: 0.004068</code></pre>
</div>
</div>
</section>
<section id="interaction-3" class="slide level2">
<h2>Interaction</h2>
<div class="v-center">
<p><img data-src="linRegInteractionPlot.png" style="width:70.0%"></p>
</div>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="linear_regression_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="linear_regression_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="linear_regression_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="linear_regression_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="linear_regression_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="linear_regression_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="linear_regression_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="linear_regression_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="linear_regression_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="linear_regression_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>