---
title: "Bayes' Rule for Events"
execute:
  echo: true
subtitle: "ISI-BUDS 2026"
format: 
  revealjs:
    slide-number: true
    incremental: true
    theme: ["../slide-style.scss"]
    title-slide-attributes: 
      data-background-size: 12%
      data-background-position: 50% 75%
---

```{r}
#| echo: false
library(bayesrules)
```






## Monty Hall problem

The problem is based on a TV game show hosted by Monty Hall. 

. . . 

In this show, contestants had the chance to win cars. Before each show, a car is put behind one of three closed doors.The other two doors have goats behind them. The contestant is asked to choose one of the three doors. 

. . . 

Then, Monty Hall then opens one of the other two doors, which he knows does not have a car behind it. After that, the contestant can choose to switch the the remaining unopened door, or stay with his original selection. 

. . . 

The question is: should they switch?

## Monty Hall problem -- Prior

At the beginning, the car can be behind any of the three doors with equal probability. 

. . .

Therefore, our **prior** (probability distribution before observing any data) can be expressed as:

\begin{eqnarray*}
P(D_1) = P(D_2) = P(D_3) = 1/3
\end{eqnarray*}


## Monty Hall problem -- Likelihood


Let's say we choose door number 1, and Monty opens door number 2. 

. . .

Now we have observed some **data**. 

. . .

Let's write down the conditional probability of this observed data, $OD_2$, given different values for the unknown parameter: $D_1, D_2$, and $D_3$:

\begin{eqnarray*}
P(OD_2|D_1) & = & 1/2\\
P(OD_2|D_2) & = & 0\\
P(OD_2|D_3) & = & 1
\end{eqnarray*}

. . .

This is called the **likelihood function**.


## Monty Hall problem -- Likelihood

Note that the likelihood function is not a probability distribution -- it doesn't add up to 1! 

. . . 

Therefore, it's common to write it as $L(\theta; D)$, or in general, $L(\theta)$.



## Marginal probability of observed data

Recall that if $B = (B_1, B_2, ..., B_n)$ are a set of events that partition the sample space,  using the **law of total probability**, we have:
\begin{eqnarray*}
P(A) & = & P(A|B_1)P(B_1)+...+P(A|B_n)P(B_n)
\end{eqnarray*}

## Monty Hall problem -- Marginal probability

Using the law of total probability we can find the marginal probability for opening door number 2:

\begin{eqnarray*}
P(OD_2) & = & P(OD_2|D_1)P(D_1) + \\
& & P(OD_2|D_2)P(D_2) + \\
& & P(OD_2|D_3)P(D_3)\\
 & = & 1/2 \times 1/3 + 0 \times 1/3 + 1 \times 1/3 = 1/2
\end{eqnarray*}



## Bayes' theorem

For two events, $A$ and $B$, **Bayes' theorem** can be simply presented as follows:
\begin{eqnarray*}
P(B|A) & = & \frac{P(B)P(A|B)}{P(A)}
\end{eqnarray*}

. . . 

This is the basis of Bayesian analysis.

## Bayes' theorem

In the Bayesian framework: 

  - $P(B)$ is the prior for the unknown event/parameter
  
  - $P(A|B)$ is the likelihood for the observed event/data $A$ given $B$
  
  - $P(A)$ is the marginal probability of the observed data (i.e., regardless of the value of $B$).

. . . 

$P(B|A)$ is the **posterior** probability: our updated knowledge (or uncerntainty) about $B$ after observing $A$.


## Monty Hall problem

Using Bayes' theorem, we have:

\begin{eqnarray*}
P(D_1 |OD_2) & = & \frac{P(D_1) P(OD_2 |D_1)}{P(OD_2)}\\
& = & \frac{1/3 \times 1/2}{1/2} = 1/3\\
P(D_3 |OD_2) & = & \frac{p(D_3)P(OD_2 |D_3)}{P(OD_2)}\\
& = & \frac{1/3 \times 1}{1/2} = 2/3
\end{eqnarray*}

. . . 

Therefore, probability of winning doubles if we switch.

. . . 

You can try this using a penny and three cups. 










## Spam email

Priya, a data science student, notices that her college's email server is using a faulty spam filter.  

. . . 

Taking matters into her own hands, Priya decides to build her own spam filter.  

. . . 

As a first step, she manually examines all emails she received during the previous month and determines that 40% of these were spam.  



## Prior 

Let event $B$ represent an event of an email being spam.

$P(B) = 0.40$

. . .

The prior model

| event       | $B$ | $B^c$ | Total |
|-------------|-----|-------|-------|
| probability | 0.4 | 0.6   | 1     |

. . . 

If Priya was to act on this prior what should she do about incoming emails?



## A possible solution

Since most email is non-spam, sort all emails into the inbox.  

. . . 

This filter would certainly solve the problem of losing non-spam email in the spam folder, but at the cost of making a mess in Priya's inbox.  



## Likelihood

Priya realizes that some emails are written in all capital letters ("all caps") and decides to look at some data. In her one-month email collection:

  - 20% of spam emails used all caps. 
  
  - But only 5% of non-spam emails used all caps.

. . .

Looking at the conditional probabilities
$P(A|B) = 0.20; \quad P(A|B^c) = 0.05$

We can conclude that all caps is more common among spam emails than non-spam emails. Thus, the email is more **likely** to be spam. 



## The posterior model

$P(B|A) = \frac{P(B)P(A|B)}{P(A)}$

. . .

Recall the Law of Total Probability:     

$P(A) = P(A|B)P(B) + P(A|B^c)P(B^c)$

. . .

Then the posterior probabilities can be obtained as follows: 

$P(B|A) = \frac{0.40 \cdot 0.20}{(0.20 \cdot 0.40) + (0.05 \cdot 0.60)} = 0.72$

$P(B^c|A) = \frac{0.60 \cdot 0.05}{(0.20 \cdot 0.40) + (0.05 \cdot 0.60)} = 0.28$

## The posterior model

The Posterior Model


| event                 | $B$  | $B^c$ | Total |
|-----------------------|------|-------|-------|
| prior probability     | 0.4  | 0.6   | 1     |
| posterior probability | 0.72 | 0.28  | 1     |



## Likelihood is not a probability distribution


| event                 | $B$  | $B^c$ | Total |
|-----------------------|------|-------|-------|
| prior probability     | 0.4  | 0.6   | 1     |
| likelihood            | 0.20 | 0.05  | 0.25  |
| posterior probability | 0.72 | 0.28  | 1     |



# Summary

$$P(B |A) = \frac{P(B)P(A|B)}{P(A)}$$

. . .

$$\text{posterior} = \frac{\text{prior}\cdot\text{likelihood}}{\text{marginal probability}}$$

. . .

$$\text{posterior} = \frac{\text{prior}\cdot\text{likelihood}}{\text{normalizing constant}}$$
